<?php
/**
 * Campaign Monitor Magento Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to license@magento.com and you will be sent a copy.
 *
 * @package Campaignmonitor_Createsend
 * @copyright Copyright (c) 2015 Campaign Monitor (https://www.campaignmonitor.com/)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php
/**
 * Template for block Campaignmonitor_Createsend_Block_Adminhtml_Email_View_Tab_Details
 */
?>
<?php
    $email = $this->getEmail();
?>
<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-customer-view"><?php echo Mage::helper('createsend')->__('Message Details') ?></h4></div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <tr>
                <td><strong><?php echo $this->__('Status:') ?></strong></td>
                <td><?php if (isset($email['Status'])){ echo htmlentities($email['Status']); } ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Sent At:') ?></strong></td>
                <td><?php if (isset($email['SentAt'])){ echo htmlentities($email['SentAt']); } ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Recipient:') ?></strong></td>
                <td>
                    <?php
                        if (isset($email['Recipient'])){
                            echo htmlentities(iconv_mime_decode($email['Recipient']));
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Subject:') ?></strong></td>
                <td>
                    <?php
                        if (isset($email['Message']['Subject'])){
                            echo htmlentities(iconv_mime_decode($email['Message']['Subject']));
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Can Be Resent:') ?></strong></td>
                <td><?php if (isset($email['CanBeResent'])){ echo ($email['CanBeResent'] ? 'Yes' : 'No'); } ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Total Opens:') ?></strong></td>
                <td><?php if (isset($email['TotalOpens'])){ echo htmlentities($email['TotalOpens']); } ?></td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('Total Clicks:') ?></strong></td>
                <td><?php if (isset($email['TotalClicks'])){ echo htmlentities($email['TotalClicks']); } ?></td>
            </tr>

        </table>
        <table cellspacing="2" class="box-right">
            <tr>
                <td><strong><?php echo $this->__('From:') ?></strong></td>
                <td>
                    <?php
                        if (isset($email['Message']['From'])){
                            echo htmlentities(iconv_mime_decode($email['Message']['From']));
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('To:') ?></strong></td>
                <td>
                    <?php
                    if (isset($email['Message']['To'])) {
                        $count = 0;
                        foreach ($email['Message']['To'] as $emailTo) {
                            if ($count++ > 0) {
                                echo ', ';
                            }

                            echo htmlentities(iconv_mime_decode($emailTo));
                        }
                    }
                    ?>
                </td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('BCC:') ?></strong></td>
                <td>
                    <?php
                        if (isset($email['Message']['BCC'])){
                            echo htmlentities(iconv_mime_decode($email['Message']['BCC']));
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <td><strong><?php echo $this->__('ReplyTo:') ?></strong></td>
                <td>
                    <?php
                        if (isset($email['Message']['ReplyTo'])){
                            echo htmlentities(iconv_mime_decode($email['Message']['ReplyTo']));
                        }
                    ?>
                </td>
            </tr>
        </table>
    </fieldset>
</div>
<?php echo $this->getChildHtml('', true, true); ?>
