<?php

$block = $this;

$adminAjaxUrl = $this->helper->getAjaxUrl();

$formKey = Mage::getSingleton('core/session')->getFormKey();
$data = Mage::getSingleton('tradesy_importer/tradesy');



$id = $data->getItemId();
$userToken = $data->getUserToken();
$shippingMethod = $data->getUserShippingMethod();
$tradesyMappedCategoryId = $data->getTradesyCategory();


$process = Mage::helper('tradesy_importer/process');


$tradesyProductId = Mage::getModel('tradesy_importer/product')->load($id, 'product_id')->getTradesyProductId();
$tradesyItem = $process->getTradesyProduct($tradesyProductId, $userToken);

echo "<pre>";
print_r($tradesyItem);
echo "</pre>";

$productInfo    = Mage::getModel('catalog/product')->load($id);
$stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($productInfo);
$brand = "";

if (!empty($tradesyItem)){
   $brand = $tradesyItem->brand;
} else {
    $manufacturer = $productInfo->getManufacturer();
    $brand = (!empty($manufacturer)) ? $manufacturer : $productInfo->getBrand();
}



$imgSrc = "";
try{
    //$imgSrc = Mage::helper('catalog/image')->init($productInfo, 'image');
    $imgSrc = Mage::getModel('catalog/product_media_config')->getMediaUrl($productInfo->getImage());
}
catch(Exception $e) {
    $imgSrc = "";
}

    $size='FAIL';
    $condition="Gently used";
    $variantID    = "";
    $item_name    = $productInfo->getName();
    $asking_price = $productInfo->getPrice();
    $item_image   = $imgSrc;
    $brand        = $brand;
    $productType  = $productInfo->getType();
    $tags         = $productInfo->getTags();
    $title        = $productInfo->getName();
    $description  = $productInfo->getDescription();
    $qty          = intval($stock->getQty());
    $compare_at_price = $productInfo->getSpecialPrice();

$propVal = Mage::helper('tradesy_importer/connect')->sendTradseyRequest("/items/property-values", "", "GET");
$catPropAr = array();
$catParentArray=array();

foreach ($propVal->message->property_values as $cat)
{
    $catId=$cat->id;
    $catPropAr[$catId]=array();
    $catPropAr[$catId]["name"]=$cat->name;
    $catPropAr[$catId]["sizes"]=array();
    $catPropAr[$catId]["condition"]=array();
    $catPropAr[$catId]["other"]=array();

    foreach ($cat->properties as $prop)
    {
        if (strpos($prop->name, "size")!==false) {
            foreach ($prop->values as $val)
            {
                $catPropAr[$catId]["sizes"][$val->id]=$val->name;//." (".$prop->name.")";//[$prop->name]
            }
        }
        elseif (strtolower($prop->name)=="condition") {
            foreach ($prop->values as $val)
            {
                $catPropAr[$catId]["condition"][$val->id]=$val->name;//." (".$prop->name.")";//[$prop->name]
            }
        }
        else{
            if (!isset($ar[$catId][$prop->name])) {
                $ar[$catId]["other"][$prop->name]=array();
            }
            foreach ($prop->values as $val) {
                $catPropAr[$catId]["other"][$prop->name][$val->id]=$val->name;//." (".$prop->name.")";//[$prop->name]
            }
        }
    }
}

// get an array of all categories with their name, parent category id, and the top category id
function setCategoryParents($cats, $parentID = 0, $parentAr = array())
{
    global $catParentArray;
    if ($parentID == 0) {
        $catParentArray = array();
    }

    foreach ($cats as $cat) {
        $catParentArray[$cat->id] = array("name" => $cat->name, "parent" => $parentID, "parents" => $parentAr);
        $tempAr=$parentAr;
        array_unshift($tempAr, $cat->id);
        if (isset($cat->subtype)) {
            setCategoryParents($cat->subtype,  $cat->id, $tempAr);
        }
        if (isset($cat->style)) {
            setCategoryParents($cat->style, $cat->id, $tempAr);
        }
    }
}

$path = '/items/categories';
$jsonData = '';
$method = 'GET';
$tradesyCategories = Mage::helper('tradesy_importer/connect')->sendTradseyRequest($path, $jsonData, $method);

setCategoryParents($tradesyCategories->message->category_tree);
$categoryDropDown = Mage::helper('tradesy_importer/connect')->categoryDropDown();


?>
<div class="tradesy-content">
<?php  if ($this->helper->isUserConnected()) : ?>

    <div class="trd-app-wrapper"><div class="trd-card">

            <h4 class="section-heading">Product Import into Tradesy</h4>
            <div style="text-align:center;">
                <img id="productImage" src="<?php echo $item_image; ?>" style="width:200px; height:200px; border:1px solid #ccc;">
                <form class="uploadImage"  id="uploadImageForm" enctype="multipart/form-data" method="post" name="startProducts" action="<?php echo Mage::helper("adminhtml")->getUrl('/tradesy/upload'); ?>">
                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                    <input type="hidden" name="product_id" value="<?php echo $id ?>" />
                    <input type="hidden" name="category_id" value="<?php echo $tradesyMappedCategoryId ?>" />

                    <input type="file" name="fileToUpload" id="fileToUpload">
                    <p class="notices"></p>
                    <input id="selectButton" type="submit" name="selectButton" class="btn small black" value="Select Image"/>
                    <input type="submit" name="" class="btn small black" value="Upload Image"/>

                </form>
            </div>

            <form class="accountForm"  id="singleProductCategoryForm" enctype="multipart/form-data" method="post" name="startProducts" action="#">
                <input type="hidden" name="id" value="<?php echo $id; ?>" />
                <input type="hidden" name="tut" value="<?php echo $userToken; ?>" />
                <input type="hidden" name="type" value="processTradesyProduct" />
                <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                <input type="hidden" name="image" value="<?php echo $item_image; ?>" />
                <?php if ($tradesyProductId > 0) : ?>
                    <input type="hidden" name="tradesy_item_id" value="<?php echo $tradesyProductId ?>" />
                <?php endif; ?>

                <div style="box-sizing: border-box; padding:10px;">
                    <table style="margin:0 auto;" id="itemUpdTable">
                        <tr><td>Title</td><td><input type="text" name="title" id="title" value="<?php echo htmlentities($item_name); ?>" /></td></tr>
                        <tr><td>Brand</td><td><input type="text" name="vendor" value="<?php echo htmlentities($brand); ?>" required/></td></tr>
                        <tr><td>Description</td><td><textarea name="description"><?php echo $description; ?></textarea></tr>
                        <tr><td>Price</td><td><input type="text" name="asking_price" id="asking_price" value="<?php echo floatval($asking_price); ?>" maxlength="8" /></td></tr>
                        <tr><td>Category</td><td><select size=1 name="categoryId" id="categoryId"><?php echo $categoryDropDown; ?></select></td></tr>
                        <tr><td>Size</td><td><select name="Size" id="Size"><option value="">&nbsp;</option></select></td></tr>
                        <tr><td>Condition</td><td><select name="Condition" id="Condition"><option value="<?php echo htmlentities($condition); ?>"><?php echo htmlentities($condition); ?></option></select></td></tr>
                        <tr id="QuantityRow"><td>Quantity</td><td><input name="quantity" type="text" value="<?php echo htmlentities($qty); ?>" /></td></tr>
                        <tr><td>Shipping</td><td id="shippingMethod">
                                <div class="optionContainer">
                                    <div><span class="radioContainer"><input type="radio" name="shippingMethod" value="1"
                                                                             id="shippingMethod1" <?php echo ($shippingMethod) ? "checked" : ""; ?> ></span><label
                                            for="shippingMethod1" class="optionLabel">Use Your Own Label &amp; Materials</label>
                                    </div>
                                    <div class="optionSubContainer"><em class="subContentLabel">Perfect When</em> - You've got your
                                        own packaging & shipping solution
                                    </div>
                                    <div class="optionSubContainer"><em class="subContentLabel">How It Works</em> - You'll submit a
                                        tracking number after you ship an item
                                    </div>
                                </div>
                                <div id="shippingPriceContainer" style="padding-left:30px;<?= (($tradesyUserDetails->default_shipping_method != 1) ? 'display:none;' : '') ?>">
                                    <div class="optionContainer">
                                        <div><span class="radioContainer"><input type="radio" name="shippingPriceType" value="perProduct"
                                                                                  id="perProductShipping"></span><label for="perProductShipping" class="optionLabel">Flat Rate</label></div>
                                        <div class="optionSubContainer">$ <input type="text" style="width:100px;display:inline-block;" value="" name="shippingPerProductAmount" id="shippingPerProductAmount" /></div>
                                    </div>
                                    <div class="optionContainer">
                                        <div><span class="radioContainer"><input type="radio" name="shippingPriceType" value="percent" id="percentShipping"></span><label for="percentShipping" class="optionLabel" name="shippingProductPercent"
                                                     id="shippingProductPercent">% Premium </label></div>
                                        <div class="optionSubContainer"><input type="text" style="width:100px;display:inline-block;" value=""
                                                                               name="shippingProductPercentAmount" id="shippingProductPercentAmount"  /> %</div>
                                    </div>
                                </div>
                                <div class="optionContainer">
                                    <div><span class="radioContainer">
                                            <input type="radio" name="shippingMethod" value="2"
                                                                             id="shippingMethod3" ></span><label
                                            for="shippingMethod3" class="optionLabel">Free Printable Label</label></div>
                                    <div class="optionSubContainer"><em class="subContentLabel">Perfect When</em> - You're set up to
                                        package and ship quickly, but would rather not deal with postage
                                    </div>
                                    <div class="optionSubContainer"><em class="subContentLabel">How it Works</em> - You'll receive
                                        instructions for printing a prepaid shipping label when your items sell
                                    </div>
                                </div>
                                <div class="optionContainer">
                                    <div><span class="radioContainer">
                                            <input type="radio" name="shippingMethod" value="0"
                                                                             id="shippingMethod4"  ></span><label
                                            for="shippingMethod4" class="optionLabel">Use Global Settings</label>
                                    </div>
                                </div>
                            </td></tr>
                        <tr><td>&nbsp;</td><td>
                                <button type="button" class="btn med black left" id="importOneProductButton">Update/Export Product</button>
                                <button type="button"  class="btn med black left" id="btnReset">Reset</button>
                                <button type="button" class="btn med black left" id="importOneProductButton">Clear Override</button>
                            </td></tr>
                    </table>
                </div>
                <div style="clear: both;"></div>
            </form>
        </div></div>

    <div class="modal-loader">
        <div class="notices"></div>
        <div class="spinner">
            <div class="double-bounce1"></div>
            <div class="double-bounce2"></div>
        </div>
    </div>
<style>
    .notices {
        text-align: center;
        position: relative;
        top:0;
        left:0;
        right:0;
        bottom:0;
        margin:auto;
        font-size: 1.3em;
    }
</style>

    <script>
        //
        function performClick(elemId) {
            var elem = document.getElementById(elemId);
            if(elem && document.createEvent) {
                var evt = document.createEvent("MouseEvents");
                evt.initEvent("click", true, false);
                elem.dispatchEvent(evt);
            }
        }
        jQuery.noConflict();

        jQuery("#btnReset").click(function(e){
            window.location.reload();
        });
       jQuery(".modal-loader").hide();

        jQuery('input[name="vendor"]').blur(function(e){

            var element = jQuery(this);
            if (element.val().length === 0) {
                element.css("outline-color", "red");
                element.css("outline-style", "solid");
            } else {
                element.attr("style","");
            }

        });

        function flashMessage(type, message){
            jQuery(".notices").text(message);
        }
        jQuery('#fileToUpload').hide();
        jQuery('#productImage').click(function(e){
            e.preventDefault();
            performClick("fileToUpload");
        });
        jQuery('#selectButton').click(function(e){
            e.preventDefault();
            performClick("fileToUpload");
        });

            jQuery("#importOneProductButton").click(function () {

                var brandInput = jQuery('input[name="vendor"]');
                if (brandInput.val().length === 0){
                    brandInput.attr("placeholder", "Required");
                    brandInput.focus();
                    return;
                }

                if (validateOneProductForm())
                {
                    jQuery(".modal-loader").slideDown();
                    flashMessage(0,"Processing the form. Please Wait...");
                   // ajaxPost("<?php echo $adminAjaxUrl; ?>", jQuery('#singleProductCategoryForm'));


                    form = jQuery('#singleProductCategoryForm');
                    jQuery.ajax({
                        type: "POST",
                        url: "<?php echo $adminAjaxUrl; ?>",
                        data: form.serialize(),
                        success: function(data, textStatus, request){
                          // location.reload();
                            //jQuery(".modal-loader").slideUp();
                           window.location.href = "<?php echo Mage::helper("adminhtml")->getUrl('/tradesy/post'); ?>";
                            console.log(request);
                        },
                        error: function (request, textStatus, errorThrown) {
                            console.log(errorThrown);
                        }
                    });

                }
            });

            function validateOneProductForm()
            {
                var catid=jQuery("#categoryId").val();

                if (catid<0 || catid.length<1)
                {
                    flashMessage(1,"Category Is Required");
                    return false;
                }

                var title=jQuery("#title").val();
                if (title.length<0)
                {
                    flashMessage(1,"Title Is Required");
                    return false;
                }

                var asking_price=jQuery("#asking_price").val();
                if (asking_price.length<0)
                {
                    flashMessage(1,"Price Is Required");
                    return false;
                }
                return true;
            }



            jQuery("#categoryId").change(function () {
                var catId=parseInt(jQuery("#categoryId").val());
                //alert(catId);
                if (catId<=0 || isNaN(catId))
                {
                    var catDisplay="";
                }
                else
                {
                    var catDisplay=" "+jQuery("#categoryId option:selected").text().trim();
                }

                var opsElem=document.getElementById("Size").options;
                var selElem=jQuery("#Size option:selected");
                var opSelVal=selElem.val();
                var opSelText=selElem.text();
                opsElem.length=0;
                var opt = document.createElement("option");
                opt.text = "--"+catDisplay+" Size --";
                opt.value = "";
                opsElem.add(opt);
                updateDropByCat("Size",catSizeAr, catId, opSelVal, opSelText);
                var opsElem=document.getElementById("Condition").options;
                var selElem=jQuery("#Condition option:selected");
                var opSelVal=selElem.val();
                var opSelText=selElem.text();
                //alert(opSelText+"!!");
                opsElem.length=0;
                var opt = document.createElement("option");
                opt.text = "--"+catDisplay+" Condition --";
                opt.value = "";
                opsElem.add(opt);
                updateDropByCat("Condition",catConditionAr,catId, opSelVal, opSelText);
                //alert("c");
                jQuery(".propRow" ).remove();
                updateOtherPropList(catId);
            });

            function updateDropByCat(elemId, opAr, catId, opSelVal, opSelText)
            {
                var catKey=catIdAr.indexOf(catId);
                //alert(catKey);
                if (catKey<0)
                {
                    return false;
                }

                if (catSizeAr[catKey].length>0)
                {
                    var opsElem=document.getElementById(elemId).options;
                    for (var x=0;x<opAr[catKey].length;x++)
                    {
                        var opt = document.createElement("option");
                        opt.value = opAr[catKey][x][1];
                        opt.text = opAr[catKey][x][1];

                        if (opSelVal==opAr[catKey][x][0] || opSelText==opAr[catKey][x][1])
                        {
                            opt.selected = true;
                        }
                        // Add an Option object to Drop Down/List Box
                        opsElem.add(opt);
                    }
                }
                else
                {
                    //alert(catParentAr[catKey]);
                    if (catParentAr[catKey].length>0)
                    {
                        updateDropByCat(elemId, opAr, catParentAr[catKey][0], opSelVal, opSelText); // catIdAr.indexOf()
                    }
                }
            }

            function updateOtherPropList(catId)
            {
                var catKey=catIdAr.indexOf(catId);
                if (catKey<0)
                {
                    return false;
                }

                for (var x1=0; x1<catPropOtherAr[catKey].length; x1++)
                {
                    var capPropOther = catPropOtherAr[catKey][x1];
                    var displayStr = capPropOther[0].substr(0,1).toUpperCase() + capPropOther[0].substr(1).replace("-"," ");
                    var fieldId = "prop-"+capPropOther[0];
                    var rowStr="<tr class='propRow'><td>"+displayStr+"</td><td><select id='"+fieldId+"' name='"+fieldId+"'><option value=''>-- "+displayStr+" --</option>";

                    var fieldK=otherPropElem.indexOf(fieldId);

                    for (var x2=0; x2<capPropOther[1].length; x2++)
                    {
                        var prop=capPropOther[1][x2];
                        var selHtml="";
                        if (fieldK>=0)
                        {
                            if (otherPropVal[fieldK]==+prop[0] || otherPropText[fieldK]==prop[1])
                            {
                                selHtml=" selected='selected'";
                            }
                        }
                        rowStr+="<option value='"+prop[1]+"'"+selHtml+">"+prop[1]+"</option>";
                    }
                    rowStr+="</td></tr>";
                    jQuery('#QuantityRow').before(rowStr);
                    jQuery('body').on('change', '#'+fieldId, function() {
                        var k=otherPropElem.indexOf(jQuery( this ).attr('id'));
                        if (k<0)
                        {
                            k=otherPropElem.length;
                            otherPropElem[k] = jQuery( this ).attr('id');
                        }
                        otherPropVal[k]=jQuery( this ).val();
                        if (otherPropVal[k].length>0)
                        {
                            otherPropText[k]=jQuery( this ).find('option:selected').text();
                        }
                        else
                        {
                            otherPropText[k]="";
                        }
                    });
                }

                if (catParentAr[catKey].length>0)
                {
                    updateOtherPropList(catParentAr[catKey][0]);
                }
            }

            var otherPropVal = [];
            var otherPropElem = [];
            var otherPropText = [];

            <?php
            echo "var catIdAr=[";
            $sep="";
            global $catParentArray;
            foreach ($catParentArray as $catId=>$cat)
            {
                echo $sep.intval($catId);
                $sep=", ";
            }
            echo "];\n";
            echo "var catParentAr=[ ";
            $sep="";
            foreach ($catParentArray as $catId=>$cat)
            {
                echo $sep."[";
                $sep2="";
                foreach ($cat["parents"] as $parId)
                {
                    echo $sep2.intval($parId);
                    $sep2=",";
                }
                $sep=",";
                echo "]";
            }
            echo " ];\n";
            echo "var catSizeAr=[";
            $sep="";
            foreach ($catParentArray as $catId=>$cat)
            {
                echo $sep."[ ";
                $sep2="";

                if (isset($catPropAr[$catId]))
                {
                    foreach ($catPropAr[$catId]["sizes"] as $propId=>$size)
                    {
                        echo $sep2."[".intval($propId).",\"".htmlentities($size)."\"]";
                        $sep2=",";
                    }
                }
                echo "]";
                $sep=", ";
            }
            echo " ];\n";
            echo "var catConditionAr=[";
            $sep="";
            foreach ($catParentArray as $catId=>$cat)
            {
                echo $sep."[ ";
                $sep2="";

                if (isset($catPropAr[$catId]))
                {
                    foreach ($catPropAr[$catId]["condition"] as $propId=>$cond)
                    {
                        echo $sep2."[".intval($propId).",\"".htmlentities($cond)."\"]";
                        $sep2=",";
                    }
                }

                echo "]";
                $sep=", ";
            }
            echo " ];\n";
            echo "var catPropOtherAr=[";
            $sep="";
            foreach ($catParentArray as $catId=>$cat)
            {
                echo $sep."[";
                $sep2="";

                if (isset($catPropAr[$catId]))
                {
                    foreach ($catPropAr[$catId]["other"] as $propName=>$CatOtherPropAr)
                    {
                        echo $sep2."[\"".htmlentities($propName)."\",[";
                        $sep3="";
                        foreach ($CatOtherPropAr as $propId=>$cond)
                        {
                            echo $sep3."[".intval($propId).",\"".htmlentities($cond)."\"]";
                            $sep3=",";
                        }
                        echo "]]";
                        $sep2=",";
                    }
                }

                echo "]";
                if (isset($catPropAr[$catId]))
                {
                    $sep=",\n";
                }
                else
                {
                 $sep=",";
                }

            }
            echo "];\n";

            ?>
            jQuery(document).ready(function ($) {

              //  jQuery('#categoryId option:eq(<?php echo $tradesyMappedCategoryId; ?>)').attr('selected', 'selected');

                var categories = jQuery("#categoryId option");


                categories.each(function(index, elem){
                    var element = $(elem);
                    if (element.val() == <?php echo $tradesyMappedCategoryId; ?>) {
                        element.attr('selected', 'selected');
                    }
                });

                jQuery("#categoryId").trigger("change");

                jQuery("#shippingPerProductAmount").focus(function (index)
                {
                    jQuery("#perProductShipping").prop("checked", true);
                    jQuery("#perProductShipping").change();
                });

                jQuery("#shippingProductPercentAmount").focus(function (index)
                {
                    jQuery("#percentShipping").prop("checked", true);
                    jQuery("#percentShipping").change();
                });


                jQuery("#shippingPriceContainer input[type='radio']").each(function (index)
                {
                    jQuery(this).change(function ()
                    {
                        jQuery( "#shippingPriceContainer .optionContainer").addClass("inactive");
                        jQuery( "#shippingPriceContainer input[type='text']").prop('disabled', true);
                        var elem=jQuery(this).parent( ).parent( ).parent(".optionContainer");
                        elem.removeClass("inactive");
                        elem.find("input[type='text']").prop('disabled', false);
                    });
                });

                jQuery("#shippingMethod input[name='shippingMethod']").each(function (index)
                {
                    jQuery(this).change(function ()
                    {
                        if (jQuery("input[name='shippingMethod']:checked").val()==1)
                        {
                            jQuery("#shippingPriceContainer").slideDown(400);
                        }
                        else
                        {
                            jQuery("#shippingPriceContainer").slideUp(100);
                        }
                    });

                });
            });



    </script>
<?php endif; ?>

</div>