<?php

$block = $this;
$currentUser = Mage::getModel('tradesy_importer/user')->getCurrent();
$userId = $currentUser->getId();

$orderTable = Mage::getModel('tradesy_importer/tradesy_order');
$orders = $orderTable->getCollection()->addFieldToFilter('user_id', $userId);
$earnings = $orderTable->getTotalEarnings($userId);

?>

<div class="tradesy-content">
    <hgroup>
        <h1 class="title"><span>Tradesy</span> - Orders</h1>
        <h2 class="short-description">The Marketplace for Luxury Fashion</h2>
    </hgroup>


   <!-- <a class="request" href="#">Request</a>-->
    <div id="message"></div>

    <div class="master-content">
        <div class="block">
            <h3>Orders</h3>
            <?php echo count($orders); ?>
        </div>
        <div class="block">
            <h3>Earnings</h3>
            <?php echo $earnings; ?>
        </div>
    </div>
</div>

<script>
    jQuery.noConflict();
    jQuery(document).ready(function($){
        jQuery(".request").click(function(e){
            e.preventDefault();
            var summary = $('#message');
            console.log($('#message').text());
            var dataToSend = "form_key=" + encodeURIComponent("<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>");

            jQuery.ajax({
                type: "POST",
                url: "<?php echo Mage::helper("adminhtml")->getUrl('/tradesy/progress') . '?isAjax=true'; ?>",
                data: dataToSend,
                success: function(data, textStatus, request){

                   console.log($(summary));
                    summary.html(data);
                },
                error: function (request, textStatus, errorThrown) {

                }
            });


        });
    });

</script>
