<?php
/**
 * Campaign Monitor Magento Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to license@magento.com and you will be sent a copy.
 *
 * @package Campaignmonitor_Createsend
 * @copyright Copyright (c) 2015 Campaign Monitor (https://www.campaignmonitor.com/)
 * @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<?php /* @var $this Mage_Core_Block_Template */ ?>
<div class="switcher">
    <label for="store_switcher"><?php echo $this->__('Scope:') ?></label>
    <?php echo $this->getHintHtml() ?>
    <select id="store_switcher" class="system-config-store-switcher" onchange="location.href=this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
        <?php if (isset($_option['is_group'])): ?>
        <?php if ($_option['is_close']): ?>
            </optgroup>
        <?php else: ?>
        <optgroup label="<?php echo $this->escapeHtml($_option['label']) ?>" style="<?php echo $_option['style'] ?>">
            <?php endif; ?>
            <?php continue ?>
            <?php endif; ?>
            <option value="<?php echo $this->escapeHtml($_value) ?>" url="<?php echo $_option['url'] ?>" <?php echo $_option['selected'] ? 'selected="selected"' : '' ?> style="<?php echo $_option['style'] ?>">
                <?php echo $this->escapeHtml($_option['label']) ?>
            </option>
            <?php endforeach ?>
    </select>
</div>